/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiveRouteImport } from './routes/live'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSearchPostsRouteImport } from './routes/api/public/search-posts'
import { Route as ApiPublicProjectsRouteImport } from './routes/api/public/projects'
import { Route as ApiPublicLiveFeedRouteImport } from './routes/api/public/live-feed'
import { Route as ApiPublicExportReportRouteImport } from './routes/api/public/export-report'
import { Route as ApiPublicDemoFlowRouteImport } from './routes/api/public/demo-flow'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'

const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSearchPostsRoute = ApiPublicSearchPostsRouteImport.update({
  id: '/api/public/search-posts',
  path: '/api/public/search-posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProjectsRoute = ApiPublicProjectsRouteImport.update({
  id: '/api/public/projects',
  path: '/api/public/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLiveFeedRoute = ApiPublicLiveFeedRouteImport.update({
  id: '/api/public/live-feed',
  path: '/api/public/live-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExportReportRoute = ApiPublicExportReportRouteImport.update({
  id: '/api/public/export-report',
  path: '/api/public/export-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDemoFlowRoute = ApiPublicDemoFlowRouteImport.update({
  id: '/api/public/demo-flow',
  path: '/api/public/demo-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/graph': typeof GraphRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRoute
  '/live': typeof LiveRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/demo-flow': typeof ApiPublicDemoFlowRoute
  '/api/public/export-report': typeof ApiPublicExportReportRoute
  '/api/public/live-feed': typeof ApiPublicLiveFeedRoute
  '/api/public/projects': typeof ApiPublicProjectsRoute
  '/api/public/search-posts': typeof ApiPublicSearchPostsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/graph': typeof GraphRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRoute
  '/live': typeof LiveRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/demo-flow': typeof ApiPublicDemoFlowRoute
  '/api/public/export-report': typeof ApiPublicExportReportRoute
  '/api/public/live-feed': typeof ApiPublicLiveFeedRoute
  '/api/public/projects': typeof ApiPublicProjectsRoute
  '/api/public/search-posts': typeof ApiPublicSearchPostsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/graph': typeof GraphRoute
  '/insights': typeof InsightsRoute
  '/journey': typeof JourneyRoute
  '/live': typeof LiveRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/demo-flow': typeof ApiPublicDemoFlowRoute
  '/api/public/export-report': typeof ApiPublicExportReportRoute
  '/api/public/live-feed': typeof ApiPublicLiveFeedRoute
  '/api/public/projects': typeof ApiPublicProjectsRoute
  '/api/public/search-posts': typeof ApiPublicSearchPostsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/graph'
    | '/insights'
    | '/journey'
    | '/live'
    | '/api/public/chat'
    | '/api/public/demo-flow'
    | '/api/public/export-report'
    | '/api/public/live-feed'
    | '/api/public/projects'
    | '/api/public/search-posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/graph'
    | '/insights'
    | '/journey'
    | '/live'
    | '/api/public/chat'
    | '/api/public/demo-flow'
    | '/api/public/export-report'
    | '/api/public/live-feed'
    | '/api/public/projects'
    | '/api/public/search-posts'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/graph'
    | '/insights'
    | '/journey'
    | '/live'
    | '/api/public/chat'
    | '/api/public/demo-flow'
    | '/api/public/export-report'
    | '/api/public/live-feed'
    | '/api/public/projects'
    | '/api/public/search-posts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GraphRoute: typeof GraphRoute
  InsightsRoute: typeof InsightsRoute
  JourneyRoute: typeof JourneyRoute
  LiveRoute: typeof LiveRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicDemoFlowRoute: typeof ApiPublicDemoFlowRoute
  ApiPublicExportReportRoute: typeof ApiPublicExportReportRoute
  ApiPublicLiveFeedRoute: typeof ApiPublicLiveFeedRoute
  ApiPublicProjectsRoute: typeof ApiPublicProjectsRoute
  ApiPublicSearchPostsRoute: typeof ApiPublicSearchPostsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/search-posts': {
      id: '/api/public/search-posts'
      path: '/api/public/search-posts'
      fullPath: '/api/public/search-posts'
      preLoaderRoute: typeof ApiPublicSearchPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/projects': {
      id: '/api/public/projects'
      path: '/api/public/projects'
      fullPath: '/api/public/projects'
      preLoaderRoute: typeof ApiPublicProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/live-feed': {
      id: '/api/public/live-feed'
      path: '/api/public/live-feed'
      fullPath: '/api/public/live-feed'
      preLoaderRoute: typeof ApiPublicLiveFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/export-report': {
      id: '/api/public/export-report'
      path: '/api/public/export-report'
      fullPath: '/api/public/export-report'
      preLoaderRoute: typeof ApiPublicExportReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/demo-flow': {
      id: '/api/public/demo-flow'
      path: '/api/public/demo-flow'
      fullPath: '/api/public/demo-flow'
      preLoaderRoute: typeof ApiPublicDemoFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GraphRoute: GraphRoute,
  InsightsRoute: InsightsRoute,
  JourneyRoute: JourneyRoute,
  LiveRoute: LiveRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicDemoFlowRoute: ApiPublicDemoFlowRoute,
  ApiPublicExportReportRoute: ApiPublicExportReportRoute,
  ApiPublicLiveFeedRoute: ApiPublicLiveFeedRoute,
  ApiPublicProjectsRoute: ApiPublicProjectsRoute,
  ApiPublicSearchPostsRoute: ApiPublicSearchPostsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
